import Packets.Incoming.LOGIN_REQUEST
import Packets.Incoming.VERSION_CONFIRM
import Packets.Incoming.CLIENT_VALIDATION
import Packets.Incoming.CLIENT_CHARACTER_LIST_REQUEST
import Packets.Incoming.CLIENT_CHARACTER_CREATE_REQUEST