import Packets.Outgoing.VERSION_CONFIRM
import Packets.Outgoing.CONSTRUCT_PACKET_HEADER
import Packets.Outgoing.LOGIN_RESPONSE
import Packets.Outgoing.CHARACTER_LIST_RESPONSE
import Packets.Outgoing.CHARACTER_CREATE_RESPONSE
import Packets.Outgoing.TRANSFER_TO_WORLD
import Packets.Outgoing.LOAD_STATIC_ZONE
import Packets.Outgoing.CREATE_CHARACTER