from Packets.Replica import BaseData
from Packets.Replica import ControllablePhysics
from Packets.Replica import Destructible
from Packets.Replica import Stats
from Packets.Replica import Character
from Packets.Replica import Inventory
from Packets.Replica import Skill
from Packets.Replica import Render
from Packets.Replica import Component107
from Packets.Replica import SimplePhysics
from Packets.Replica import PhantomPhysics
from Packets.Replica import Vendor
from Packets.Replica import Script